#ifndef COMMAND_H
#define COMMAND_H

enum class Command_Type {
	NOTE,
	DRUM_NOTE,
	REST,
	OCTAVE,
	NOTE_TYPE,
	DRUM_SPEED,
	TRANSPOSE,
	TEMPO,
	DUTY_CYCLE,
	VOLUME_ENVELOPE,
	DUTY_CYCLE_PATTERN,
	PITCH_SLIDE,
	VIBRATO,
	TOGGLE_NOISE,
	FORCE_STEREO_PANNING,
	VOLUME,
	PITCH_OFFSET,
	STEREO_PANNING,
	SOUND_JUMP,
	SOUND_LOOP,
	SOUND_CALL,
	SOUND_RET,
};

static const char * const COMMAND_NAMES[] = {
	"NOTE",
	"DRUM_NOTE",
	"REST",
	"OCTAVE",
	"NOTE_TYPE",
	"DRUM_SPEED",
	"TRANSPOSE",
	"TEMPO",
	"DUTY_CYCLE",
	"VOLUME_ENVELOPE",
	"DUTY_CYCLE_PATTERN",
	"PITCH_SLIDE",
	"VIBRATO",
	"TOGGLE_NOISE",
	"FORCE_STEREO_PANNING",
	"VOLUME",
	"PITCH_OFFSET",
	"STEREO_PANNING",
	"SOUND_JUMP",
	"SOUND_LOOP",
	"SOUND_CALL",
	"SOUND_RET",
};

struct Command {
	Command_Type command_type;
};

#endif
